### ISSUE TITLE
'npm start' error with protractor

### ISSUE THREAD

**Issue by scottcarlton** [angular/quickstart#325]
Trying to run quickstart `npm start` and get the following on Mac Pro Sierra v10.12.1.
npm -v // 3.10.9
tsc -v // 2.1.4

I can run `npm lite` and server starts up, but any cli common with tsc (npm tsc, npm tsc:w) gets the errors below. I can run tsc outside the quickstart dir and everything works fine. I checked my node_modules permissions and seems correct. Any suggestions? Thanks

`node_modules/protractor/built/browser.d.ts(260,37): error TS2503: Cannot find namespace 'webdriver'.`
`node_modules/protractor/built/browser.d.ts(267,55): error TS2503: Cannot find namespace 'webdriver'.`
`node_modules/protractor/built/browser.d.ts(267,78): error TS2503: Cannot find namespace 'webdriver'.`
`node_modules/protractor/built/browser.d.ts(358,31): error TS2503: Cannot find namespace 'webdriver'.`
`node_modules/protractor/built/browser.d.ts(369,26): error TS2503: Cannot find namespace 'webdriver'.`
`node_modules/protractor/built/browser.d.ts(425,36): error TS2503: Cannot find namespace 'webdriver'.`
`node_modules/protractor/built/ptor.d.ts(13,29): error TS2503: Cannot find namespace 'webdriver'.`

**Comment by jtdewey** [comment]
I am experiencing a similar error on Windows.
```
C:\quickstart>npm start

> angular-quickstart@1.0.0 start C:\Users\dewey\src\quickstart
> tsc && concurrently "tsc -w" "lite-server"

node_modules/protractor/built/browser.d.ts(260,37): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(267,55): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(267,78): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(358,31): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(369,26): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/browser.d.ts(425,36): error TS2503: Cannot find namespace 'webdriver'.
node_modules/protractor/built/ptor.d.ts(13,29): error TS2503: Cannot find namespace 'webdriver'.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\dewey\src\quickstart\npm-debug.log
```

**Comment by abductedMind** [comment]
Exact same problem here.

**Comment by nickJones67** [comment]
instead of 
`>npm start`
try
`>npm run lite`

**Comment by abductedMind** [comment]
@nickJones67 That runs, but please explain why.

**Comment by JPCortesP** [comment]
@nickJones67 it works, however, the *.ts aren't updating the *.js...

**Comment by nickJones67** [comment]
**@abductedMind** Not sure. I discovered it on [this] (https://github.com/angular/angular/issues/6097) issue discussion
**@JPCortesP** Yes this a pretty big problem.

**Comment by JPCortesP** [comment]
I managed to get it running using two terminal windows, one with npm run tsc:w other with npm run lite

**Comment by filipesilva** [comment]
This seems to be related with a `@types` problem. Can you try using this exact one?
```
@types/selenium-webdriver@2.53.33
```

**Comment by JPCortesP** [comment]
@filipesilva it works now. Wonder what's the inner problem with the newer version?

**Comment by filipesilva** [comment]
Not too sure myself but @cnishina is working on it I believe.

**Comment by ramiromd** [comment]
Same problem using Debian 8.6.0 Jessie.
$ node -v
v6.9.1

$ npm -v
3.10.8

**Comment by daintym0sh** [comment]
@nickJones67  thanks for your help `>npm run lite` works.. i've been confused for an hour!

**Comment by Lloydinator** [comment]
Man this was driving me mad for an hour, especially after seeing `npm run lite` run (but without my controllers working). Tried installing selenium manually and same thing. So glad I stopped by here. Thanks so much @filipesilva. Hope this thing is resolved soon.

**Comment by daintym0sh** [comment]
If anyone is still confused, 

change the following in package.json 

  `"start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" "` 
to 
`"start": "concurrently \"npm run tsc:w\" \"npm run lite\" "`

reference: [http://stackoverflow.com/questions/34335340/angular2-quickstart-npm-start-is-not-working-correctly](url)

**Comment by scottcarlton** [comment]
@daintym0sh thanks changing that `npm start` seems to work though those errors still persist but doesn't seem to effect the build.

`6:11:24 PM - File change detected. Starting incremental compilation...`
`[0] node_modules/protractor/built/browser.d.ts(260,37): error TS2503: Cannot find namespace 'webdriver'.`
`[0] node_modules/protractor/built/browser.d.ts(267,55): error TS2503: Cannot find namespace 'webdriver'.`
`[0] node_modules/protractor/built/browser.d.ts(267,78): error TS2503: Cannot find namespace 'webdriver'.`
`[0] node_modules/protractor/built/browser.d.ts(358,31): error TS2503: Cannot find namespace 'webdriver'.`
`[0] node_modules/protractor/built/browser.d.ts(369,26): error TS2503: Cannot find namespace 'webdriver'.`
`[0] node_modules/protractor/built/browser.d.ts(425,36): error TS2503: Cannot find namespace 'webdriver'.`
`[0] node_modules/protractor/built/ptor.d.ts(13,29): error TS2503: Cannot find namespace 'webdriver'.`
`[0] 6:11:25 PM - Compilation complete. Watching for file changes.`
`[1] [BS] File changed: app/app.component.js`

**Comment by andresrinivasan** [comment]
Per @filipesilva, rather than modify package.json, use a specific version of selenium-webdriver:

npm install @types/selenium-webdriver@2.53.33

**Comment by jtdewey** [comment]
Can confirm that on Windows the only needed change is changing this line `package.json` from
```
    "@types/selenium-webdriver": "^2.53.33"
```
to
```
    "@types/selenium-webdriver": "2.53.33"
```
Then an `npm install` and `npm start` should work like normal.

👏 @filipesilva @andresrinivasan

**Comment by scottcarlton** [comment]
@jtdewey can confirm this solution working on Mac too. Thanks! @filipesilva @andresrinivasan

**Comment by scottcarlton** [comment]
Going to close this issue for now.

**Comment by filipesilva** [comment]
Just to let people know, a fix is on the works in https://github.com/angular/protractor/pull/3848.

**Comment by filipesilva** [comment]
I'm going to reopen this since more people are opening new issues to report it.

**Comment by memento** [comment]
This trick didn't work for me (Ubuntu 14.04 )

> Can confirm that on Windows the only needed change is changing this line package.json from
> 
>     "@types/selenium-webdriver": "^2.53.33"
> to
> 
>     "@types/selenium-webdriver": "2.53.33"
> Then an npm install and npm start should work like normal.

I had to use this command to start :

```
npm run lite
```

I have npm version 4.1.1

**Comment by EdwardMudaida** [comment]
Try npm run serve
